# Generated by Django 4.0.7 on 2022-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0002_email_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.EmailField(max_length=200),
        ),
    ]
